config/routes.rb
# == Route Map
#
#          Prefix Verb   URI Pattern                Controller#Action
# locations_index GET    /locations/index(.:format) locations#index
#   locations_new GET    /locations/new(.:format)   locations#new
#  locations_edit GET    /locations/edit(.:format)  locations#edit
#  locations_show GET    /locations/show(.:format)  locations#show
#            root GET    /                          pages#home
#           users POST   /users(.:format)           users#create
#        new_user GET    /users/new(.:format)       users#new
#          events GET    /events(.:format)          events#index
#                 POST   /events(.:format)          events#create
#       new_event GET    /events/new(.:format)      events#new
#      edit_event GET    /events/:id/edit(.:format) events#edit
#           event GET    /events/:id(.:format)      events#show
#                 PATCH  /events/:id(.:format)      events#update
#                 PUT    /events/:id(.:format)      events#update
#                 DELETE /events/:id(.:format)      events#destroy

Rails.application.routes.draw do

  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :update, :index]
  get '/users/edit' => 'users#edit', :as => :edit_user
  get '/users/:id/events' => 'users#events', :as => 'user_events'
  get '/users/events' => 'users#events'
  get '/users/:id/qrs' => 'users#qrs', :as => 'user_qrs'

  resources :events  #, :only => [:new, :create]
  post '/events/:id/attend' => 'events#attend', :as => 'attend_event'

  resources :locations

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#  name            :text
#  admin           :boolean
#  image           :text
#  dob             :date
#  phone           :text
#

class User < ApplicationRecord
  has_secure_password

  # Validations -- see the Rails Guide
  validates :email, :presence => true, :uniqueness => true
  has_many :attends
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_login, :only => [:edit, :update, :events]
  before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params # Set up the user but don't save yet.
    if @user.save # .save returns true if the user is valid, and false otherwise.
      session[:user_id] = @user.id # Login when signing up.
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = @current_user
  end

  def update
    @current_user.update user_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @current_user.image = req["public_id"]
    end
    @current_user.update user_params
    @current_user.save
    redirect_to root_path
  end

  def events
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :image, :dob, :phone)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Update your profile</h1>
<div class="card text-white bg-secondary mb-3" style="max-width: 28rem;">
  <div class="card-body">
    <%= form_for @user, :html => {:multipart => true} do |f| %>
      <div class="form-group">
        <%= f.label :email %>
        <div class="col-sm">
          <%= f.email_field :email, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :name %>
        <div class="col-sm">
          <%= f.text_field :name, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :dob, "Date of birth" %>
        <div class="col-sm">
          <%= f.date_field :dob, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :phone, "Mobile number" %>
        <div class="col-sm">
          <%= f.text_field :phone, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :image %>
          <div class="col-sm">
            <%= f.cl_image_upload :image, :class => 'form-control' %>
          </div>
      </div>

      <%= f.submit "Update profile", :class => "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/users/events.html.erb
<h1>My Events</h1>
<div class="card-columns">
  <% @current_user.attends.each do |attend| %>
    <div class="card" style="width: 18rem;">
      <%= image_tag attend.event.image, :class => "card-img-top" %>
        <div class="card-body text-center">
          <%= link_to attend.event.title, event_path(attend.event_id), :class => "card-title" %>
        </div>
    </div>
  <% end %>
</div>

<div class="card mb-3">
  <div class="card-body">
  <div id="calendar">
  </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>

<div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
  <div class="card-body">
    <% @users.each do |user| %>
      <p><%= user.email %></p>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>
<div class="card text-white bg-secondary mb-3" style="max-width: 28rem;">
  <div class="card-body">
    <% if @user.errors.any? %>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :email %>
        <div class="col-sm">
          <%= f.email_field :email, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <div class="col-sm">
          <%= f.password_field :password, :class => 'form-control'%>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <div class="col-sm">
          <%= f.password_field :password_confirmation, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :image %>
          <div class="col-sm">
            <%= f.url_field :image, :class => 'form-control', :value => "https://cdn.pixabay.com/photo/2017/07/18/23/23/user-2517433_960_720.png" %>
          </div>
      </div>

      <%= f.submit "Sign up!", :class => "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/qrs.html.erb
<h1>My QR Code</h1>

    <% @current_user.attends.each do |attend| %>
      <div class="card text-center">
        <div class="card-header">
          <%= link_to attend.event.title, event_path(attend.event_id) %>
        </div>
        <div class="card-body">
            <% @qr = RQRCode::QRCode.new(attend.provisioning_uri("Events_app"), :size => 10, :level => :h ) %>
            <table class="qr">
              <% @qr.modules.each_index do |x| %>
                  <tr>
                    <% @qr.modules.each_index do |y| %>
                        <% if @qr.dark?(x,y) %>
                            <td class="black"/>
                        <% else %>
                            <td class="white"/>
                        <% end %>
                    <% end %>
                  </tr>
              <% end %>
            </table>
        </div>
    <% end %>