config/routes.rb
# == Route Map
#
#          Prefix Verb   URI Pattern                Controller#Action
# locations_index GET    /locations/index(.:format) locations#index
#   locations_new GET    /locations/new(.:format)   locations#new
#  locations_edit GET    /locations/edit(.:format)  locations#edit
#  locations_show GET    /locations/show(.:format)  locations#show
#            root GET    /                          pages#home
#           users POST   /users(.:format)           users#create
#        new_user GET    /users/new(.:format)       users#new
#          events GET    /events(.:format)          events#index
#                 POST   /events(.:format)          events#create
#       new_event GET    /events/new(.:format)      events#new
#      edit_event GET    /events/:id/edit(.:format) events#edit
#           event GET    /events/:id(.:format)      events#show
#                 PATCH  /events/:id(.:format)      events#update
#                 PUT    /events/:id(.:format)      events#update
#                 DELETE /events/:id(.:format)      events#destroy

Rails.application.routes.draw do

  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :update, :index]
  get '/users/edit' => 'users#edit', :as => :edit_user
  get '/users/:id/events' => 'users#events', :as => 'user_events'
  get '/users/events' => 'users#events'
  get '/users/:id/qrs' => 'users#qrs', :as => 'user_qrs'

  resources :events  #, :only => [:new, :create]
  post '/events/:id/attend' => 'events#attend', :as => 'attend_event'

  resources :locations

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'


end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :bigint           not null, primary key
#  title       :text
#  start_date  :datetime
#  image       :text
#  address     :text
#  info        :text
#  location_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  end_date    :datetime
#

class Event < ApplicationRecord
  belongs_to :location, :optional => true
  has_many :attends
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :check_for_login, :only => [:attend]
  before_action :check_for_admin, :only => [:new, :edit, :destroy]

  def index
    @events = Event.all.order(:start_date)
  end

  def new
    @event = Event.new
  end

  def create
    event = Event.create event_params
    if params[:file].present?
      # Then call Cloudinary's upload method, passing in the file in params
      req = Cloudinary::Uploader.upload(params[:file])
      # Using the public_id allows us to use Cloudinary's powerful image
      # transformation methods.
      event.image = req["public_id"]
      event.save
    end
    redirect_to event
  end

  def edit
    @event = Event.find params[:id]
  end

  def update
    event = Event.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      event.image = req["public_id"]
    end
    event.update event_params
    event.save
    redirect_to event
  end

  def show
    @event = Event.find params[:id]
  end

  def destroy
    event = Event.find params[:id]
    event.destroy
    redirect_to events_path
  end

  def attend
    event = Event.find params[:id]
    attend = Attend.create(:user_id => @current_user.id, :event_id => event.id)
    attend.save
    redirect_to event
  end

  private
    def event_params
    # Strong parameters: whitelist of sanitised input -- stuff we are happy to let the user provide us.
    params.require(:event).permit(:title, :start_date, :end_date, :image, :address, :info, :location_id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="card text-white bg-secondary mb-3" style="max-width: 50rem;">
  <div class="card-body">
    <%= form_for @event, :html => {:multipart => true} do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, :autofocus => true, :required => true, :class => 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :date %>
        <%= f.text_field :start_date, :placeholder => 'DD-MM-YYYY, H:MM am', :class => 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :end_date %>
        <%= f.text_field :end_date, :placeholder => 'DD-MM-YYYY, H:MM pm', :class => 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, :class => 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :info %>
        <%= f.text_field :info, :class => 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :image %>
        <%= f.cl_image_upload :image, :class => 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :location_id %>
        <%= f.select :location_id, Location.pluck(:name, :id), :include_blank => true, :class => 'form-control' %>
      </div>
      <%= f.submit "Update", :class => "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render :partial => 'form' %>

app/views/events/index.html.erb
<h1>All Events</h1>
<div class="card-columns">
  <% @events.each do |event| %>
    <div class="card" style="width: 22rem;">
      <%= cl_image_tag event.image, :class => "card-img-top" %>
        <div class="card-body">
          <h5 class="card-title"><%= event.title %></h5>
          <ul class="card-text">
              <li>Title: <%= link_to event.title, event %></li>
              <li>Date: <%= event.start_date.strftime '%a, %b %e %Y, %l:%M %P' %> to <%= event.end_date.strftime '%a, %b %e %y, %l:%M %P' %></li>
              <li>Address: <%= event.address %></li>
            </ul>
        </div>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render :partial => 'form' %>

app/views/events/show.html.erb
<div class="card mb-3">
  <%= cl_image_tag @event.image, :class=>"card-img-top" %>
    <div class="card-body">
      <h2 class="card-title"><%= @event.title %></h2>
      <ul class="card-text">
        <li>Title: <%= @event.title %></li>
          <li>Date: <%= @event.start_date.strftime '%a, %b %e %Y, %l:%M %P' %> to <%= @event.end_date.strftime '%a, %b %e %Y, %l:%M %P' %> </li>
        <li>Address: <%= @event.address %></li>
        <% if @event.location.present? %>
        <li>Explore location: <%= link_to @event.location.name, @event.location %></li>
        <% end %>
      </ul>
      <p class="card-text"><%= @event.info if @event.info.present?%></p>
      <%= button_to "Attend!", attend_event_path(@event), :method => 'post', :class => "btn btn-outline-warning" %>
    </div>
</div>

<div class="card mb-3">
  <div class="card-body">
    <p class="card-title">Attendee:</p>
    <ul>
      <li class="img-attendee">
        <% @event.attends.each do |attend| %>
          <%= cl_image_tag attend.user.image, :class => 'img-attendee rounded-circle' if attend.user.image.present? %>
        <% end %>
      </li>
    </ul>
  </div>
</div>


<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <div class="controls">
      <%= link_to "Edit event", edit_event_path(@event), :class => "breadcrumb-item" %>
      <%= link_to "Delete event", @event, :method => 'delete', :class => "breadcrumb-item active", :data => {:confirm => 'Are you sure?'} %>
    </div>
  </ol>
</nav>