config/routes.rb
# == Route Map
#
#          Prefix Verb   URI Pattern                Controller#Action
# locations_index GET    /locations/index(.:format) locations#index
#   locations_new GET    /locations/new(.:format)   locations#new
#  locations_edit GET    /locations/edit(.:format)  locations#edit
#  locations_show GET    /locations/show(.:format)  locations#show
#            root GET    /                          pages#home
#           users POST   /users(.:format)           users#create
#        new_user GET    /users/new(.:format)       users#new
#          events GET    /events(.:format)          events#index
#                 POST   /events(.:format)          events#create
#       new_event GET    /events/new(.:format)      events#new
#      edit_event GET    /events/:id/edit(.:format) events#edit
#           event GET    /events/:id(.:format)      events#show
#                 PATCH  /events/:id(.:format)      events#update
#                 PUT    /events/:id(.:format)      events#update
#                 DELETE /events/:id(.:format)      events#destroy

Rails.application.routes.draw do

  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :update, :index]
  get '/users/edit' => 'users#edit', :as => :edit_user
  get '/users/:id/events' => 'users#events', :as => 'user_events'
  get '/users/events' => 'users#events'
  get '/users/:id/qrs' => 'users#qrs', :as => 'user_qrs'

  resources :events  #, :only => [:new, :create]
  post '/events/:id/attend' => 'events#attend', :as => 'attend_event'

  resources :locations

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'


end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :bigint           not null, primary key
#  name       :text
#  image      :text
#  event_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Location < ApplicationRecord
  has_many :events
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :check_for_admin, :only => [:new, :edit, :destroy]

  def index
    @locations = Location.all.order(:name)
  end

  def new
    @location = Location.new
  end

  def create
    location = Location.create location_params
    if params[:file].present?
      # Then call Cloudinary's upload method, passing in the file in params
      req = Cloudinary::Uploader.upload(params[:file])
      # Using the public_id allows us to use Cloudinary's powerful image
      # transformation methods.
      location.image = req["public_id"]
      location.save
    end
    redirect_to location
  end

  def edit
    @location = location.find params[:id]
  end

  def updated
    location = Location.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      location.image = req["public_id"]
    end
    location.update location_params
    location.save
    redirect_to location
  end

  def show
    @location = Location.find params[:id]
  end

  def destroy
    location = Location.find params[:id]
    location.destroy
    redirect_to locations_path
  end

  private
  def location_params
    params.require(:location).permit(:name, :image, :event_id)
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<div class="card text-white bg-secondary mb-3" style="max-width: 50rem;">
  <div class="card-body">
    <%= form_for @location, :html => {:multipart => true} do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, :class => 'form-control'%>
      </div>
      <div class="form-group">
        <%= f.label :image %>
        <%= f.cl_image_upload :image, :required => true, :class => 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :event_id %>
        <%= f.select :event_id, Event.pluck(:title, :id), :include_blank => true, :class => 'form-control' %>
      </div>
      <%= f.submit "Update", :class => "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/locations/edit.html.erb
<h1>Edit Location</h1>

<%= render :partial => 'form' %>

app/views/locations/index.html.erb
<h1>All Locations</h1>
<div class="card-columns">
  <% @locations.each do |location| %>
    <div class="card text-center" style="width: 22rem;">
      <%= cl_image_tag location.image, :class => 'card-img-top' %>
      <div class="card-body">
        <h5 class="card-text"><%= link_to location.name, location %></h5>
      </div>
    </div>
  <% end %>
</div>

app/views/locations/new.html.erb
<h1>Location</h1>

<%= render :partial => 'form' %>

app/views/locations/show.html.erb
<div class="card mb-3">
  <%= cl_image_tag @location.image, :class=>"card-img-top" %>
    <div class="card-body">
    <h1 class="card-title"><%= @location.name %></h1>
  </div>
</div>

<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">More event in this area</h5>
      <% @location.events.each do |event| %>
        <%= link_to cl_image_tag(event.image, :class => 'img-fluid img-thumbnail rounded img-event-in-location'), event %>
      <% end %>
  </div>
</div>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <div class="controls">
      <%= link_to "Localocation", edit_location_path(@location), :class => "breadcrumb-item" %>
      <%= link_to "Delete location", @location, :method => 'delete', :class => "breadcrumb-item active", :data => {:confirm => 'Are you sure?'} %>
    </div>
  </ol>
</nav>