config/routes.rb
# == Route Map
#
#          Prefix Verb   URI Pattern                Controller#Action
# locations_index GET    /locations/index(.:format) locations#index
#   locations_new GET    /locations/new(.:format)   locations#new
#  locations_edit GET    /locations/edit(.:format)  locations#edit
#  locations_show GET    /locations/show(.:format)  locations#show
#            root GET    /                          pages#home
#           users POST   /users(.:format)           users#create
#        new_user GET    /users/new(.:format)       users#new
#          events GET    /events(.:format)          events#index
#                 POST   /events(.:format)          events#create
#       new_event GET    /events/new(.:format)      events#new
#      edit_event GET    /events/:id/edit(.:format) events#edit
#           event GET    /events/:id(.:format)      events#show
#                 PATCH  /events/:id(.:format)      events#update
#                 PUT    /events/:id(.:format)      events#update
#                 DELETE /events/:id(.:format)      events#destroy

Rails.application.routes.draw do

  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :update, :index]
  get '/users/edit' => 'users#edit', :as => :edit_user
  get '/users/:id/events' => 'users#events', :as => 'user_events'
  get '/users/events' => 'users#events'
  get '/users/:id/qrs' => 'users#qrs', :as => 'user_qrs'

  resources :events  #, :only => [:new, :create]
  post '/events/:id/attend' => 'events#attend', :as => 'attend_event'

  resources :locations

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EVENTWISH</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= cloudinary_js_config %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#"><img src="https://png.pngtree.com/element_origin_min_pic/17/08/14/d3deba206624f5062e76dec31c4bb4c7.jpg" width="30" height="30" class="d-inline-block align-top nav_brand" alt=""> EVENTWISH</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav bd-navbar-nav flex-row">
          <li class="nav-item active">
          <%= link_to "Home", root_path, :class => "nav-link" %>
          </li>
          <% if @current_user.present? %>
          <li class="nav-item">
            <%= link_to "EVENTS", events_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "LOCATIONS", locations_path, :class => "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "My EVENTWISH", user_events_path(@current_user), :class=>"dropdown-item" %>
              <%= link_to "QR POCKET", user_qrs_path(@current_user), :class=>"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "My Profile", edit_user_path, :class => "dropdown-item" %>
            </div>
          </li>
          <% if @current_user.admin? %>
          <li class="nav-item">
            <%= link_to "All Users", users_path, :class => "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            CREATE NEW
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'New Event', new_event_path, :class=>"dropdown-item" %>
              <%= link_to 'New Location', new_location_path, :class=>"dropdown-item" %>
            </div>
          </li>
            <% end %>
          </ul>
        <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
          <li class="nav-item">
            <%= cl_image_tag @current_user.image, :class=>"d-inline-block align-top nav_photo" if @current_user.image.present? %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout #{ @current_user.email }", login_path, :method => 'delete', :class => "nav-link" %>
          </li>
            <% else %>
          <li class="nav-item ">
            <%= link_to "Register", new_user_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign in", login_path, :class => "nav-link" %>
          </li>
      <% end %>
      </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>